version: '2'
services:
  web:
    build:
      context: ./run
    env_file:
      - ./run/.env.local
    ports:
      - "8080:8080"
    volumes:
      - ./run:/usr/src/app
      - /usr/src/app/node_modules